'use client';
import { useState } from 'react';
import type { Character } from '../../lib/rpg/types';
import { compareItems, equipItem } from '../../lib/rpg/equipment-system';
import { itemPower } from '../../lib/rpg/engine';

export function InventoryPanel({character,onChange}:{character:Character;onChange:(character:Character)=>void}){
 const [selected,setSelected]=useState<string|null>(null); const items=character.equipment; const chosen=items.find(i=>i.id===selected); const equipped=items.filter(i=>i.ownerId?.startsWith('equipped:'));
 return <div className="inventory-panel"><div className="inventory-toolbar"><strong>Equipment</strong><span>{items.length} items</span></div><div className="inventory-grid">{items.map(item=><button key={item.id} className={selected===item.id?'active':''} onClick={()=>setSelected(item.id)}><b>{item.name}</b><small>{item.rarity} · {item.rank} · Q{item.quality}</small><span>Power {itemPower(item)}</span></button>)}</div>{chosen&&<div className="item-inspector"><h3>{chosen.name}</h3><p>{chosen.category} · {chosen.rarity} · {chosen.rank}-Rank · Quality {chosen.quality}%</p><p>Affixes: {chosen.affixes.map(a=>a.name).join(', ')||'None'}</p><p>Soul Resonance {chosen.soulResonance}% · Condition {chosen.condition}%</p>{equipped.length>0&&<p>Equipped: {equipped.map(i=>i.name).join(', ')}</p>}<div className="item-actions">{(chosen.category==='Weapon'||chosen.category==='Armor'||chosen.category==='Accessory')&&<button onClick={()=>{const slot=chosen.category==='Weapon'?'Weapon':chosen.category==='Armor'?'Armor':'Accessory';const current=equipped.find(i=>i.ownerId===`equipped:${slot}`);if(current){const delta=compareItems(chosen,current);if(delta.powerDelta<0&&delta.qualityDelta<0)return;}onChange(equipItem(character,chosen.id,slot).character)}}>Equip</button>}{equipped.length>0&&currentCompare(equipped,chosen)&&<span>{currentCompare(equipped,chosen)}</span>}</div></div>}</div>
}
function currentCompare(equipped:any[],chosen:any){const slot=chosen.category==='Weapon'?'Weapon':chosen.category==='Armor'?'Armor':chosen.category==='Accessory'?'Accessory':null;if(!slot)return null;const current=equipped.find(i=>i.ownerId===`equipped:${slot}`);if(!current)return 'No equipped item';const d=compareItems(chosen,current);return `Power ${d.powerDelta>=0?'+':''}${d.powerDelta} · Quality ${d.qualityDelta>=0?'+':''}${d.qualityDelta}`;}
