export type QuestOutcome = 'complete' | 'fail' | 'branch';
export interface QuestChoice { id:string; label:string; consequence:string; outcome:QuestOutcome; reputationDelta?:number; goldDelta?:number; unlocks?:string[]; }
export interface QuestDefinition { id:string; title:string; description:string; choices:QuestChoice[]; requiredFlags?:string[]; }
export interface QuestState { active:string[]; completed:string[]; failed:string[]; flags:Record<string,boolean>; reputation:Record<string,number>; }
export const QUESTS:QuestDefinition[]=[
 {id:'ashen-bell',title:'The Ashen Bell',description:'A forbidden bell rings beneath Emberfall.',choices:[{id:'investigate',label:'Descend beneath the bell tower',consequence:'Reveal the sealed chamber.',outcome:'complete',goldDelta:120,unlocks:['ash-chamber']},{id:'warn-guild',label:'Warn the Adventurer Guild',consequence:'The guild mobilizes and changes the local threat state.',outcome:'branch',reputationDelta:8,unlocks:['guild-mobilization']},{id:'ring-back',label:'Ring the bell in response',consequence:'Something on the other side answers.',outcome:'branch',unlocks:['veil-response']}]},
 {id:'wolves-greyfen',title:'Wolves of Greyfen',description:'A corrupted pack is moving toward settlements.',choices:[{id:'hunt',label:'Hunt the alpha',consequence:'Reduce the migration threat.',outcome:'complete',goldDelta:85,unlocks:['greyfen-safe']},{id:'study',label:'Track the corruption source',consequence:'Discover the deeper cause.',outcome:'branch',unlocks:['greyfen-corruption']}]}
];
export function chooseQuest(state:QuestState,quest:QuestDefinition,choiceId:string):QuestState{const choice=quest.choices.find(c=>c.id===choiceId);if(!choice)throw new Error('Unknown quest choice');const next={...state,flags:{...state.flags},active:state.active.filter(id=>id!==quest.id),completed:[...state.completed],failed:[...state.failed]};for(const f of choice.unlocks??[])next.flags[f]=true;if(choice.outcome==='complete')next.completed.push(quest.id);if(choice.outcome==='fail')next.failed.push(quest.id);return next;}
