'use client';
import { useEffect, useMemo, useState } from 'react';
import { generateDungeon } from '../../lib/rpg/dungeon-engine';
import { AssetSprite } from '../../components/rpg/AssetSprite';
import { DungeonGridScene } from '../../components/rpg/DungeonGridScene';
import { SaveControls } from '../../components/rpg/SaveControls';
import { RoleEvolutionPanel } from '../../components/rpg/RoleEvolutionPanel';
import { CombatPanel } from '../../components/rpg/CombatPanel';
import { InventoryPanel } from '../../components/rpg/InventoryPanel';
import { TravelNav } from '../../components/rpg/TravelNav';
import { CheckpointController } from '../../components/rpg/CheckpointController';
import { createSocialState, type SocialState } from '../../lib/rpg/social-runtime';
import { validateSaveProfile } from '../../lib/rpg/canonical-save';
import { hydrateProfile } from '../../lib/rpg/profile-bridge';
import type { GameState } from '../../lib/rpg/types';
import type { CheckpointKind } from '../../lib/rpg/autosave';
import type { EncounterRuntime } from '../../lib/rpg/monster-encounter-runtime';
import { aren, monsters } from '../../lib/rpg/content';

function initialGameState():GameState{return {day:18,hour:23,location:'Emberfall — Lower Ward',character:structuredClone(aren),party:[structuredClone(aren)],activeMonster:structuredClone(monsters[0]),economy:{inflation:2.4,trust:87,prices:{iron:14,mithril:240,manaCrystal:91},treasuryReserves:{gold:900000,mana:72000}},logs:['Expedition started.']};}
function readPendingProfile(){if(typeof window==='undefined')return null;try{const raw=sessionStorage.getItem('veilbound.pendingProfile');if(!raw)return null;sessionStorage.removeItem('veilbound.pendingProfile');return validateSaveProfile(JSON.parse(raw));}catch{return null;}}
function readLegacyState(){if(typeof window==='undefined')return null;try{const raw=sessionStorage.getItem('veilbound.pendingState');if(!raw)return null;sessionStorage.removeItem('veilbound.pendingState');return JSON.parse(raw) as GameState;}catch{return null;}}

export default function GamePage(){
 const [seed,setSeed]=useState(()=>Date.now()); const [room,setRoom]=useState(0); const [gameState,setGameState]=useState<GameState>(()=>initialGameState()); const [social,setSocial]=useState<SocialState>(()=>createSocialState()); const [log,setLog]=useState<string[]>(['Expedition started.']); const [checkpointKind,setCheckpointKind]=useState<CheckpointKind>('boot'); const [checkpointTrigger,setCheckpointTrigger]=useState(0); const [encounter,setEncounter]=useState<EncounterRuntime>({active:false});
 const dungeon=useMemo(()=>generateDungeon(seed,'C',12),[seed]);
 function checkpoint(kind:CheckpointKind){setCheckpointKind(kind);setCheckpointTrigger(v=>v+1);}
 useEffect(()=>{const profile=readPendingProfile();if(profile){const hydrated=hydrateProfile(profile);setGameState(hydrated.game);setSocial(hydrated.social);setSeed(hydrated.dungeonSeed);setRoom(Math.max(0,Math.min(11,hydrated.roomIndex)));setLog(hydrated.game.logs.length?hydrated.game.logs:['Game loaded.']);checkpoint('boot');return;}const legacy=readLegacyState();if(legacy){setGameState(legacy);setLog(legacy.logs.length?legacy.logs:['Game loaded.']);checkpoint('boot');}},[]);
 const current=dungeon.rooms[room]; const roomAsset=current.kind==='Treasure'?'prop.chest.iron':current.kind==='Shrine'?'prop.shrine.basic':(current.kind==='Combat'||current.kind==='Elite'||current.kind==='Boss')?'monster.slime.verdant':'hero.human.warrior';
 function updateState(nextState:GameState){setGameState(nextState);setLog(nextState.logs.length?nextState.logs:['Game updated.']);const first=nextState.logs[0]??'';if(/defeated/i.test(first)){setEncounter({active:false});checkpoint('combat-victory');}}
 function handleEncounter(nextGame:GameState,nextEncounter:EncounterRuntime){setGameState(nextGame);setEncounter(nextEncounter);setLog(l=>[`Engaged ${nextEncounter.monster?.name ?? 'monster'}.`,...l].slice(0,20));checkpoint('dungeon-room');}
 function next(){const nextRoom=Math.min(dungeon.rooms.length-1,room+1);setRoom(nextRoom);setEncounter({active:false});setGameState(s=>({...s,logs:[`Entered room ${nextRoom+1}.`,...s.logs].slice(0,20)}));setLog(l=>[`Entered room ${nextRoom+1}.`,...l]);checkpoint('dungeon-room');}
 function resolveRoom(){setGameState(s=>({...s,logs:[`Resolved ${current.kind}.`,...s.logs].slice(0,20)}));checkpoint('dungeon-room');}
 function doorMove(delta:number){const target=Math.max(0,Math.min(dungeon.rooms.length-1,room+delta));if(target!==room){setRoom(target);setEncounter({active:false});setGameState(s=>({...s,logs:[`Entered room ${target+1} through a door.`,...s.logs].slice(0,20)}));setLog(l=>[`Entered room ${target+1} through a door.`,...l]);checkpoint('dungeon-room');}}
 return <main className="rpg-shell"><header className="topbar"><div className="brand"><span className="brand-mark">✦</span><div><b>VEILBOUND</b><small>Expedition · Combat + Equipment</small></div></div><div className="top-stats"><span>◈ {gameState.character.gold}</span><span>Lv {gameState.character.level}</span><span>Role {gameState.character.role?.core ?? 'Unawakened'}</span><span><CheckpointController slot={1} game={gameState} social={social} dungeonSeed={seed} roomIndex={room} kind={checkpointKind} trigger={checkpointTrigger}/></span></div></header><section className="hero-strip"><div><span className="eyebrow">PROCEDURAL DUNGEON</span><h1>{dungeon.name}</h1><p>Seed {seed} · Rank {dungeon.rank} · {dungeon.rooms.length} rooms</p></div></section><section className="game-grid"><section className="center-column"><div className="panel"><div className="panel-title"><span>ROOM {room+1} / {dungeon.rooms.length}</span><span>DANGER {current.danger}</span></div><div className="dungeon-scene"><DungeonGridScene room={current} onRoomChange={doorMove} game={gameState} onEncounter={handleEncounter}/></div><div className="enemy-stage"><h2>{current.kind}{encounter.active?` · ${encounter.monster?.name ?? 'Encounter'}`:''}</h2><p>Reward Tier {current.rewardTier} · Connections {current.connections.length}</p></div>{(current.kind==='Combat'||current.kind==='Elite'||current.kind==='Boss'||encounter.active)?<CombatPanel game={gameState} onGameUpdate={updateState}/>:<div className="combat-actions"><button onClick={resolveRoom}>Resolve Room</button><button onClick={next}>Explore Next Room</button></div>}</div><div className="panel log-panel"><div className="panel-title">EXPEDITION LOG</div>{log.slice(0,10).map((x,i)=><p key={`${x}-${i}`}><time>•</time>{x}</p>)}</div></section><aside className="panel right-panel"><TravelNav state={gameState}/><h2>Dungeon Route</h2>{dungeon.rooms.map((r,i)=><button key={r.id} onClick={()=>{setRoom(i);setEncounter({active:false});checkpoint('dungeon-room')}} className={i===room?'active':''} style={{display:'block',width:'100%',textAlign:'left',marginBottom:6}}>{i+1}. {r.kind} · danger {r.danger}</button>)}<div className="asset-preview"><strong>Asset Layer</strong><p>Logical ID: <code>{roomAsset}</code></p><AssetSprite id={roomAsset} alt="Current asset" className="asset-preview-img"/></div><InventoryPanel character={gameState.character} onChange={character=>setGameState(s=>({...s,character}))}/>{gameState.character.role&&<RoleEvolutionPanel state={gameState.character.role}/>}<SaveControls state={gameState} onLoad={updateState}/></aside></section><footer>VEILBOUND · Dungeon ↔ Town ↔ World · canonical autosave restore active</footer></main>;
}
