'use client';
import { useMemo, useState } from 'react';
import { generateDungeon } from '../../lib/rpg/dungeon-engine';

export default function GamePage(){
 const [seed]=useState(()=>Date.now()); const dungeon=useMemo(()=>generateDungeon(seed,'C',12),[seed]); const [room,setRoom]=useState(0); const [hp,setHp]=useState(100); const [gold,setGold]=useState(340); const [log,setLog]=useState<string[]>(['Expedition started.']);
 const current=dungeon.rooms[room];
 function act(){ if(current.kind==='Combat'||current.kind==='Elite'||current.kind==='Boss'){setHp(v=>Math.max(1,v-(current.danger%13+4)));setGold(v=>v+current.rewardTier*8);setLog(l=>[`Cleared ${current.kind} encounter. +${current.rewardTier*8} gold.`,...l]);} else {setGold(v=>v+current.rewardTier*5);setLog(l=>[`Resolved ${current.kind} room.`,...l]);} }
 function next(){setRoom(v=>Math.min(dungeon.rooms.length-1,v+1));setLog(l=>[`Entered room ${Math.min(room+2,dungeon.rooms.length)}.`,...l]);}
 return <main className="rpg-shell"><header className="topbar"><div className="brand"><span className="brand-mark">✦</span><div><b>VEILBOUND</b><small>Expedition Prototype</small></div></div><div className="top-stats"><span>HP {hp}/100</span><span>◈ {gold}</span></div></header><section className="hero-strip"><div><span className="eyebrow">PROCEDURAL DUNGEON</span><h1>{dungeon.name}</h1><p>Seed {seed} · Rank {dungeon.rank}</p></div></section><section className="game-grid"><section className="center-column"><div className="panel combat-panel"><div className="panel-title"><span>ROOM {room+1} / {dungeon.rooms.length}</span><span>DANGER {current.danger}</span></div><div className="enemy-stage"><div className="rune">◈</div><div className="enemy-icon">{current.kind==='Boss'?'☠':current.kind==='Treasure'?'◆':current.kind==='Puzzle'?'◇':'⚔'}</div><h2>{current.kind}</h2><p>Reward Tier {current.rewardTier}</p></div><div className="combat-actions"><button onClick={act}>Resolve Room</button><button onClick={next}>Explore Next Room</button></div></div><div className="panel log-panel"><div className="panel-title">EXPEDITION LOG</div>{log.slice(0,10).map((x,i)=><p key={i}><time>•</time>{x}</p>)}</div></section><aside className="panel right-panel"><h2>Dungeon Route</h2>{dungeon.rooms.map((r,i)=><button key={r.id} onClick={()=>setRoom(i)} className={i===room?'active':''} style={{display:'block',width:'100%',textAlign:'left',marginBottom:6}}>{i+1}. {r.kind} · danger {r.danger}</button>)}</aside></section><footer>VEILBOUND · Playable systems prototype</footer></main>;
}
