'use client';
import { useMemo, useState } from 'react';
import { NPCS, QUEST_BOARD, availableQuests, talkToNpc } from '../../lib/rpg/npc-engine';

export default function NpcsPage(){
 const [hour]=useState(18); const [selected,setSelected]=useState(NPCS[0].id); const [flags,setFlags]=useState<Record<string,boolean|string|number>>({}); const [rep,setRep]=useState<Record<string,number>>({'adventurer-guild':25,blacksmiths:12,'veil-wardens':30}); const npc=NPCS.find(n=>n.id===selected)!; const dialogue=useMemo(()=>talkToNpc(npc,rep,flags,hour),[npc,rep,flags]); const quests=availableQuests(rep,flags);
 function accept(id:string){const q=QUEST_BOARD.find(x=>x.id===id);if(!q)return;setFlags(f=>({...f,[`quest:${id}`]:true}));setRep(r=>({...r,[q.factionId]:(r[q.factionId]??0)+2}));}
 return <main className="rpg-shell"><header className="topbar"><div className="brand"><span className="brand-mark">✦</span><div><b>VEILBOUND</b><small>NPCs · Quest Board</small></div></div></header><section className="hero-strip"><div><span className="eyebrow">SOCIAL SYSTEM</span><h1>Valerion Guild Hall</h1><p>NPC mood and available work react to reputation and world flags.</p></div></section><section className="game-grid"><section className="center-column"><div className="panel"><div className="panel-title">NPCs</div>{NPCS.filter(n=>n.location==='Valerion').map(n=><button key={n.id} onClick={()=>setSelected(n.id)} className={selected===n.id?'active':''} style={{display:'block',width:'100%',textAlign:'left',marginBottom:8}}><b>{n.name}</b> · {n.title}<small style={{display:'block'}}>{n.personality}</small></button>)}<div className="lore"><b>{npc.name}</b><p>{dialogue.text}</p><p>Mood: {dialogue.mood} · Faction rep: {rep[npc.factionId]??0}</p></div></div><div className="panel"><div className="panel-title">QUEST BOARD</div>{quests.filter(q=>npc.questIds.includes(q.id)||npc.id==='captain-elian').map(q=><article key={q.id} className="shop-item"><div><b>{q.title}</b><p>{q.summary}</p><small>Lv {q.level} · +{q.rewardXp} XP · +{q.rewardGold} gold</small></div><button onClick={()=>accept(q.id)} disabled={Boolean(flags[`quest:${q.id}`])}>{flags[`quest:${q.id}`]?'Accepted':'Accept'}</button></article>)}</div></section><aside className="panel right-panel"><h2>World State</h2>{Object.entries(rep).map(([k,v])=><p key={k}>{k}: {v}</p>)}<h2>Flags</h2>{Object.keys(flags).length?Object.entries(flags).map(([k,v])=><p key={k}>{k}: {String(v)}</p>):<p>No active local flags.</p>}<button className="gold-btn" onClick={()=>setFlags(f=>({...f,'veil-response':true}))}>Simulate Veil Response</button></aside></section><footer>VEILBOUND · NPC schedules · faction-aware dialogue · quest availability</footer></main>;
}
