'use client';
import { useEffect, useMemo, useState } from 'react';
import { useRouter } from 'next/navigation';
import { createTown, buyFromShop } from '../../lib/rpg/town-engine';
import { items } from '../../lib/rpg/content';
import { loadTravelState, storeTravelState } from '../../lib/rpg/travel';
import type { GameState } from '../../lib/rpg/types';

function baseState():GameState{return {day:18,hour:18,location:'Valerion',character:structuredClone({id:'town-hero',name:'Aster',race:'Human',level:1,xp:0,gold:100,attributes:{STR:10,VIT:10,MAG:10,SPD:10,INT:10,SKL:10},profession:{id:'wanderer',name:'Wanderer',level:1,xp:0,rank:'F',branches:[]},skills:[],equipment:[],reputation:0,role:{origin:'Wanderer',core:'Unawakened',rank:'F',convictions:{},achievements:[],counters:{}}}),party:[],activeMonster:{id:'none',name:'None',rank:'F',level:1,hp:1,maxHp:1,attributes:{STR:0,VIT:0,MAG:0,SPD:0,INT:0,SKL:0,THR:0},skills:[],weaknesses:[],rewardXp:0,rewardGold:0},economy:{inflation:2,trust:80,prices:{iron:14,mithril:240,manaCrystal:91},treasuryReserves:{gold:900000,mana:72000}},logs:[]};}
export default function TownPage(){const router=useRouter();const [game,setGame]=useState<GameState>(()=>baseState());const town=useMemo(()=>createTown('valerion','Valerion',items,1.08),[]);const [message,setMessage]=useState('Welcome to Valerion.');useEffect(()=>{const pending=loadTravelState();if(pending)setGame(pending);},[]);function buy(id:string){const result=buyFromShop(game,town,id);setGame(result.game);setMessage(result.error??'Purchase complete.');}function dungeon(){storeTravelState({...game,location:'Emberfall — Lower Ward'});router.push('/game');}return <main className="rpg-shell"><header className="topbar"><div className="brand"><span className="brand-mark">✦</span><div><b>VEILBOUND</b><small>Valerion Market</small></div></div><div className="top-stats"><span>◈ {game.character.gold}</span><span>Rep {game.character.reputation}</span></div></header><section className="hero-strip"><div><span className="eyebrow">TOWN</span><h1>{town.name}</h1><p>Inn · Blacksmith · Adventurer Guild · General Store</p></div></section><section className="game-grid"><section className="center-column"><div className="panel"><div className="panel-title">SHOP</div>{town.shop.map(listing=><article key={listing.id} className="shop-item"><div><b>{listing.item.name}</b><p>{listing.item.rarity} · Rank {listing.item.rank} · Quality {listing.item.quality}</p><small>{listing.item.affixes.map(a=>a.name).join(' · ')||'No affixes'}</small></div><div><strong>◈ {listing.price}</strong><button onClick={()=>buy(listing.id)} disabled={listing.stock<=0}>Buy</button></div></article>)}<p>{message}</p></div></section><aside className="panel"><h2>Character</h2><p>{game.character.name}</p><p>Gold: {game.character.gold}</p><p>Equipment: {game.character.equipment.length}</p><button onClick={dungeon}>Enter Expedition</button></aside></section><footer>VEILBOUND · Town economy preview · state-preserving travel</footer></main>}
