'use client';
import { useMemo, useState } from 'react';
import { aren, monsters } from '../../lib/rpg/content';
import { createSimulation, chooseAshenBell, type WorldSimulation } from '../../lib/rpg/simulation-runtime';
import { getNode, travelPlan, WORLD_MAP } from '../../lib/rpg/world-map-engine';
import type { GameState } from '../../lib/rpg/types';
import { WorldSaveControls } from '../../components/rpg/WorldSaveControls';

function baseState():GameState{return {day:18,hour:23,location:'Emberfall',character:structuredClone(aren),party:[structuredClone(aren)],activeMonster:structuredClone(monsters[0]),economy:{inflation:2.4,trust:87,prices:{iron:14,mithril:240,manaCrystal:91},treasuryReserves:{gold:900000,mana:72000}},logs:['The Veil shivers above Emberfall.']};}
function nodeId(location:string){return location.toLowerCase().replaceAll(' ','-').replace(' — lower ward','');}
export default function WorldPage(){
 const [sim,setSim]=useState<WorldSimulation>(()=>createSimulation(baseState()));
 const [selected,setSelected]=useState('valerion');
 const current=getNode(nodeId(sim.game.location)) ?? getNode('emberfall')!;
 const target=getNode(selected);
 const plan=useMemo(()=>current&&target?travelPlan(current.id,target.id,sim.game.character.level):null,[current,target,sim.game.character.level]);
 const choose=(choice:'investigate'|'warn-guild'|'ring-back')=>setSim(s=>chooseAshenBell(s,choice));
 function travel(){if(!plan){setSim(s=>({...s,events:[...s.events,'No direct route to selected destination.']}));return;} if(sim.game.character.gold<plan.goldCost){setSim(s=>({...s,events:[...s.events,'Not enough gold for travel.']}));return;} const next={...sim,game:{...sim.game,character:{...sim.game.character,gold:sim.game.character.gold-plan.goldCost},location:target?.name??sim.game.location,logs:[`Travelled to ${target?.name??'unknown'} · risk ${(plan.risk*100).toFixed(0)}%`,...sim.game.logs].slice(0,20)}};setSim(next);}
 return <main className="rpg-shell"><header className="topbar"><div className="brand"><span>✦</span><div><b>VEILBOUND</b><small>Overworld Atlas · Live Simulation</small></div></div><div className="top-stats"><span>◈ {sim.game.character.gold}</span><span>Lv {sim.game.character.level}</span><span>Risk {(sim.travelRisk*100).toFixed(0)}%</span></div></header><section className="hero-strip"><div><span className="eyebrow">WORLD MAP</span><h1>{current.name}</h1><p>{current.region} · Danger {current.danger} · Level {current.level}</p></div></section><section className="game-grid"><section className="center-column"><div className="panel map-panel"><div className="map-canvas">{WORLD_MAP.map(n=><button key={n.id} className={`map-node ${n.id===current.id?'current':''} ${n.id===selected?'selected':''}`} onClick={()=>setSelected(n.id)} disabled={!n.unlocked}><span>{n.kind}</span><b>{n.name}</b><small>Lv {n.level} · {n.danger}</small></button>)}</div></div><div className="panel"><div className="panel-title">THE ASHEN BELL</div><p>A forbidden bell is ringing beneath Emberfall.</p><div className="combat-actions"><button onClick={()=>choose('investigate')}>Investigate</button><button onClick={()=>choose('warn-guild')}>Warn the Guild</button><button onClick={()=>choose('ring-back')}>Ring the Bell</button></div></div><div className="panel log-panel"><div className="panel-title">WORLD EVENTS</div>{sim.events.map((e,i)=><p key={`${e}-${i}`}><time>•</time>{e}</p>)}</div></section><aside className="panel right-panel"><h2>Travel</h2><p>Destination: <b>{target?.name}</b></p>{plan?<><p>Distance: {plan.distance}</p><p>Gold Cost: ◈ {plan.goldCost}</p><p>Travel Risk: {(plan.risk*100).toFixed(0)}%</p><p>Encounter Chance: {(plan.encounterChance*100).toFixed(0)}%</p></>:<p>No direct route.</p>}<button onClick={travel} disabled={!plan||target?.id===current.id}>Travel</button><h2>Factions</h2>{sim.factions.map(f=><div key={f.id} className="inventory"><b>{f.name}</b><p>{f.standing} · Rep {f.reputation} · Favors {f.favors}</p></div>)}<h2>Economy</h2><div className="lore"><p>Iron {sim.market.prices.iron}</p><p>Mithril {sim.market.prices.mithril}</p><p>Mana Crystal {sim.market.prices.manaCrystal}</p><p>Monster Core {sim.market.prices['monster-core']}</p><p>Treasury {Math.round(sim.market.treasury).toLocaleString()}</p><p>Inflation {(sim.market.inflation*100).toFixed(2)}%</p></div><h2>World Flags</h2><div className="lore">{Object.keys(sim.flags).length?Object.entries(sim.flags).map(([k,v])=><p key={k}>{k}: {String(v)}</p>):<p>No global flags yet.</p>}</div><WorldSaveControls simulation={sim} onLoad={setSim}/></aside></section><footer>VEILBOUND · Cities, regions and dungeons are connected by systemic travel risk</footer></main>;
}
