'use client';
import { useState } from 'react';
import { aren, monsters } from '../../lib/rpg/content';
import { createSimulation, chooseAshenBell, type WorldSimulation } from '../../lib/rpg/simulation-runtime';
import type { GameState } from '../../lib/rpg/types';

function baseState():GameState{return {day:18,hour:23,location:'Emberfall — Lower Ward',character:structuredClone(aren),party:[structuredClone(aren)],activeMonster:structuredClone(monsters[0]),economy:{inflation:2.4,trust:87,prices:{iron:14,mithril:240,manaCrystal:91},treasuryReserves:{gold:900000,mana:72000}},logs:['The Veil shivers above Emberfall.']};}
export default function WorldPage(){
 const [sim,setSim]=useState<WorldSimulation>(()=>createSimulation(baseState()));
 const choose=(choice:'investigate'|'warn-guild'|'ring-back')=>setSim(s=>chooseAshenBell(s,choice));
 return <main className="rpg-shell"><header className="topbar"><div className="brand"><span>✦</span><div><b>VEILBOUND</b><small>Live World Simulation</small></div></div><div className="top-stats"><span>Risk {(sim.travelRisk*100).toFixed(0)}%</span><span>Inflation {(sim.market.inflation*100).toFixed(2)}%</span></div></header><section className="hero-strip"><div><span className="eyebrow">WORLD CONSEQUENCE ENGINE</span><h1>{sim.game.location}</h1><p>Events propagate across factions, markets and travel routes.</p></div></section><section className="game-grid"><section className="center-column"><div className="panel"><div className="panel-title"><span>THE ASHEN BELL</span><span>ACTIVE</span></div><div style={{padding:24}}><p>A forbidden bell is ringing beneath Emberfall.</p><div className="combat-actions"><button onClick={()=>choose('investigate')}>Investigate</button><button onClick={()=>choose('warn-guild')}>Warn the Guild</button><button onClick={()=>choose('ring-back')}>Ring the Bell</button></div></div></div><div className="panel log-panel"><div className="panel-title">WORLD EVENTS</div>{sim.events.map((e,i)=><p key={`${e}-${i}`}><time>•</time>{e}</p>)}</div></section><aside className="panel right-panel"><h2>Factions</h2>{sim.factions.map(f=><div key={f.id} className="inventory"><b>{f.name}</b><p>{f.standing} · Rep {f.reputation} · Favors {f.favors}</p></div>)}<h2>Economy</h2><div className="lore"><p>Iron {sim.market.prices.iron}</p><p>Mithril {sim.market.prices.mithril}</p><p>Mana Crystal {sim.market.prices.manaCrystal}</p><p>Monster Core {sim.market.prices['monster-core']}</p><p>Treasury {Math.round(sim.market.treasury).toLocaleString()}</p></div><h2>World Flags</h2><div className="lore">{Object.keys(sim.flags).length?Object.entries(sim.flags).map(([k,v])=><p key={k}>{k}: {String(v)}</p>):<p>No global flags yet.</p>}</div></aside></section><footer>VEILBOUND · Choices are world events, not cosmetic dialogue only.</footer></main>;
}
